### ISSUE TITLE
Setup testing environment for visual tracking

### ISSUE THREAD

**Issue by weitingchou** [TopPano/AIResearch#6]
In order to know the performance of our visual trackers, we should create a new repo for setting up the testing environment for validating them. The repo should responsible for:
1. Preparing the visual tracking benchmark dataset. This could be a script to polling the dataset from their sources, we don't have to maintain the dataset in this repo.
2. Providing a Python interface for accessing the dataset by frameworks like Tensorflow or Caffe.
3. Providing a web interface for showing and comparing the result of the benchmark among one or more trackers.

For user who wants to evaluate his tracker performance, he is responsible to provide a test script of his own project, the test script can use the Python interface mentioned above to evaluate his tracker on the benchmark. Then he could clone his project to the test machine, which has pre-installed the benchmark repo in global, and run the test, the result can be viewed via web interface provided by benchmark repo.

**Comment by SuJiaKuan** [comment]
Dataset for testing includes:
1. VOT
